### ISSUE TITLE
Home Page --> Banners

### ISSUE THREAD

**Issue by rukku3** [gak112/IBSTESTING#10]
Each banner should be hyperlinked or should have "Learn More" which would be linked to it's respective page. 

Easy Business Solutions -  https://www.intellectbusiness.com/products.html
Cloud Services : https://intellectbusiness.omshriram.com/#/services/cloudsevices
Data Engineering : https://intellectbusiness.omshriram.com/#/services/dataengineering
Mobile Apps: http://ibsmobileapps.com/
UI/UX Services:  No link.  Just leave as it is
AI Solutions : No link. Just leave as it is

**Comment by srinuheroictechno** [comment]
completed
